-- Seed is intentionally empty.
--
-- The real source catalog lives in data/sources.json and is loaded with:
--     cd backend && python scripts/import_sources.py
--
-- (Kept as a separate importer because it upserts on homepage_url and is
-- idempotent, which is friendlier than a static SQL seed for 70+ sources.)
--
-- Sources exist only to attribute posted article URLs to a known outlet
-- (publisher name and logo); they no longer drive a feed of their own.
